services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AYO_URL: ${NEXT_PUBLIC_AYO_URL}

    image: songdis-web:dev
    container_name: songdis-web-dev

    environment:
      NODE_ENV: production

    ports:
      - "127.0.0.1:3001:3000"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 1G

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
